/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.senegas.tacticeditor;

import java.awt.EventQueue;

import javax.swing.JFrame;
import javax.swing.WindowConstants;

import org.senegas.tacticeditor.view.MainPanel;

public class TacticEditorApp {

	public static void main(String[] args) {
		EventQueue.invokeLater(() -> new TacticEditorApp().create());
	}

	private void create() {
		final JFrame f = new JFrame("Open Kick Off Tactic Editor");
		f.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
		f.add(new MainPanel());
		f.pack();
		f.setLocationRelativeTo(null);
		f.setVisible(true);
	}
}
